### ISSUE TITLE
Numbering Issue

### ISSUE THREAD

**Issue by PreetiRS** [learn-co-curriculum/git-basics-lab-phase-0#1]
In "Getting Started" portion of this assignment, the action items go from 1) to 3). 

I do not know if this is an error in assigning the accurate numerical value or if the second step is missing.

**Comment by lizbur10** [comment]
Hi there! Thanks for bringing this to our attention. The error has now been fixed.

Thanks for contributing to the Flatiron School curriculum. 💙
